name: SimpleQuests
version: '${version}'
main: dev.jsinco.simplequests.SimpleQuests
api-version: '1.20'
softdepend:
  - Vault
commands:
  simplequests:
    description: Main command for SimpleQuests
    permission: simplequests.command
    aliases:
      - quests
      - sq
permissions:
  simplequests.command:
    description: Main permission for SimpleQuests
    default: op